### ISSUE TITLE
うまく動いていないようなので改善を進める

### ISSUE THREAD

**Issue by nukaga** [jawordpressorg/wapuu-api#74]
うまく動いていないようなので改善を進めたいです。
WordCamp Japan のコントリビューターデイズで「わぷーを描こう」というコントリビュートグループがあり、詳細ではありませんが検証していただいたところ
- GitHubとTravisとの連携がうまくいってないのではないか
- Travisの仕様がかわったのでは
という話が出ました。

GitHub Actionsに変えた方が良いのでは、ついでにレイアウトも柔軟に配置できるように変えられないかという話も出たので、共有しておきます。

**Comment by 466548** [comment]
- わぷーの画像の高さ等、バラバラなのでCSS調整が必要
- わぷーFAQなど目を一度通して、改善すべき箇所があるかみんなで検討

できたらいいなと思います

**Comment by mirucon** [comment]
たぶん travis-ci.org 使ってて、これが終了したのが原因で動いてなさそう。travis-ci.com に移行しないといけなかったのをやってないんですね
そんな難しくないので、GitHub Actions 化、暇なときやりましょうか？

**Comment by nukaga** [comment]
@mirucon わー！ありがとうございます！素敵です！

**Comment by nukaga** [comment]
@mirucon さんのおかげで一旦動くようになったので、issueとしては閉じます！
これからの改善内容はそれぞれ別のissueとして立てて進められればと思います！

> わぷーの画像の高さ等、バラバラなのでCSS調整が必要
> わぷーFAQなど目を一度通して、改善すべき箇所があるかみんなで検討
